CREATE TABLE MST_DOMAINS(SID INT NOT NULL, DOMAINNAME VARCHAR2(100), DOMAINVAL VARCHAR2(100));

INSERT INTO MST_DOMAINS VALUES(1, 'D_RETRYATTEMPTS', '3');
INSERT INTO MST_DOMAINS VALUES(2, 'D_TIMETOWAIT', '3000');